### ISSUE TITLE
incompatible with python3.14

### ISSUE THREAD

**Issue by glyph** [ronaldoussoren/modulegraph#60]
The `imp` module has been removed in favor of `importlib` in 3.14.

**Comment by ronaldoussoren** [comment]
I pushed a new release earlier today (0.19.7) that passes all tests on Python 3.14.

**Comment by ronaldoussoren** [comment]
That said, I'm leaving this issue open until I've ported py2app to Python 3.14.  I'm hoping to get there this weekend...

**Comment by jmroot** [comment]
> I pushed a new release earlier today (0.19.7) that passes all tests on Python 3.14.

Excellent, thank you.

**Comment by jmroot** [comment]
BTW, I'm still seeing the `test_find_module` failure when I run the tests locally with 0.19.7.

**Comment by glyph** [comment]
> That said, I'm leaving this issue open until I've ported py2app to Python 3.14. I'm hoping to get there this weekend...

Thanks so much for looking at this, and good luck!
